export declare const logoColor: string;
export declare const striped: string;
export declare const stripedButton: string;
export declare const stripedLink: string;
export declare const stripedText: string;
export declare const unityGreen: string;
export declare const unityPurple: string;
export declare const unityRed: string;
export declare const unityYellow: string;
