export declare const after: string;
export declare const content: string;
export declare const home: string;
export declare const left: string;
export declare const link: string;
export declare const linkContainer: string;
export declare const logo: string;
export declare const nav2: string;
export declare const right: string;
