name: Check

on:
  push:
  workflow_dispatch:

env:
  PNPM_VERSION: "8.6"

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0

      - name: Install PNPM
        run: curl -sL https://unpkg.com/@pnpm/self-installer | node

      - name: Get PNPM store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup PNPM cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --reporter=append-only

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
